version: '3.9'

services:
  api:
    build: .
    container_name: nest_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_NAME=/data/database.sqlite
    volumes:
      - sqlite_data:/data
    restart: always

volumes:
  sqlite_data: